[SQUSH][DNM] Merge tag 'android-9.0.0_r16' into lineage-16.0
commit dbf4b11b1158137e55342d250f624196a8912e07
Merge: 252878e88 fbe26c723
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Mon Jul 30 03:00:37 2018 +0000

    Snap for 4920102 from fbe26c723af60b101a6df9c066c1b661b6ab966c to pi-qpr1-release

    Change-Id: Ifd7027234368d31d675303934b1f0f8b6e23d714

commit fbe26c723af60b101a6df9c066c1b661b6ab966c
Merge: 6fffb2332 495993289
Author: TreeHugger Robot <treehugger-gerrit@google.com>
Date:   Fri Jul 27 19:36:50 2018 +0000

    Merge "remove bionic-compile-time-tests-g++" into pi-dev

commit 252878e88968a67291099078862824dae7dc75c0
Merge: 866374163 6fffb2332
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Fri Jul 27 03:03:53 2018 +0000

    Snap for 4916303 from 6fffb2332ca3be3abee84810b389a29b731887ee to pi-qpr1-release

    Change-Id: If8971618ca5839bb3044dd35acbd31189ebb613e

commit 4959932899064afd107737bb54cbf146f2a5a518
Author: Sajid Dalvi <sdalvi@google.com>
Date:   Mon Jul 23 10:33:40 2018 -0500

    remove bionic-compile-time-tests-g++

    make checkbuild gives the following error:
    bionic/tests/fortify_filecheck_diagnostics_test.cpp:1:0: error: unknown value 'cortex-a55' for -mcpu

    The error is because we have a clang to support the new architecture,
    but not a corresponding GCC. It is not trivial to filter out an invalid
    CPU, and since there is no platform code built with GCC any more, its
    better to remove bionic-compile-time-tests-g++

    Bug: 74404306
    Change-Id: I6aa181c652abeef782fec6380dfadd066140b8b9

commit 6fffb2332ca3be3abee84810b389a29b731887ee
Author: Christopher Ferris <cferris@google.com>
Date:   Tue Jul 10 14:45:24 2018 -0700

    Disable malloc debug intercepts when exiting.

    There is a hang when enabling leak_track since the dumping of the
    leak data can wind up doing an allocation.

    Add new system unit test to make sure this doesn't happen again.

    Bug: 111146059

    Test: Test program that leaks does not hang forever.
    Test: Unit tests pass.
    Change-Id: Icf99be58ba5db98ee124a471b957a086045f5870
    Merged-In: Icf99be58ba5db98ee124a471b957a086045f5870
    (cherry picked from commit 97b474710225bc4853ab314c3d9ca812dc375525)

commit 866374163a1164e1113a4d2e9e0453d68a06dfa3
Merge: 03cb53a17 9893d6d0f
Author: Tom Cherry <tomcherry@google.com>
Date:   Mon Jul 2 16:02:52 2018 +0000

    Merge "Reland "Remove a check for AIDs in the OEM range."" into pi-dev

commit 9893d6d0ff2be5a6cdfb944df17b394678a7e340
Author: Tom Cherry <tomcherry@google.com>
Date:   Fri Jun 29 10:39:43 2018 -0700

    Reland "Remove a check for AIDs in the OEM range."

    There may be vendor extensions to the system image which would need to
    use these IDs.

    This reverts commit 41986a013a10c6f79822002800a9afe90efba4f2.

    Bug: 110856218
    Test: these tests

Change-Id: Ic8a77512f4e1fc8f3999cbaaa121e5754c1286df