Update patch set 2
Patch Set 2:

This breaks the build for Encore (omap3):
/home/david/SSD/ANDROID/cm-11.0/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.7/bin/../lib/gcc/arm-linux-androideabi/4.7/../../../../arm-linux-androideabi/bin/ld: error: /home/david/SSD/ANDROID/cm-11.0/out/target/product/encore/obj/STATIC_LIBRARIES/libc_common_intermediates/libc_common.a(memchr.o): multiple definition of 'memchr'
/home/david/SSD/ANDROID/cm-11.0/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.7/bin/../lib/gcc/arm-linux-androideabi/4.7/../../../../arm-linux-androideabi/bin/ld: /home/david/SSD/ANDROID/cm-11.0/out/target/product/encore/obj/STATIC_LIBRARIES/libc_common_intermediates/libc_common.a(memchr.o): previous definition here
collect2: error: ld returned 1 exit status
make: *** [/home/david/SSD/ANDROID/cm-11.0/out/target/product/encore/obj/SHARED_LIBRARIES/libc_intermediates/LINKED/libc.so] Error 1
Reverting it fixes the build.

Patch-set: 2
Reviewer: David Marble <2644@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0