Update patch set 1
Patch Set 1:

This causes a build error for me.

FAILED: /mnt/Data/AndroidBuilds/RR/out/soong/build.ninja 
/mnt/Data/AndroidBuilds/RR/out/soong/.bootstrap/bin/soong_build  -t -b  /mnt/Data/AndroidBuilds/RR/out/soong -d /mnt/Data/AndroidBuilds/RR/out/soong/build.ninja.d -o /mnt/Data/AndroidBuilds/RR/out/soong/build.ninja Android.bp
error: bionic/libc/Android.bp:1142:20: unrecognized property "arch.arm64.kryo300"

Patch-set: 1
CC: Joshua Leivenzon <19704@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>